# Generated by Django 5.1.3 on 2024-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_name", models.CharField(max_length=200)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="MemberData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.IntegerField(unique=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("joining_date", models.DateTimeField(auto_now_add=True)),
                ("dob", models.DateField()),
                ("address", models.TextField(blank=True, null=True)),
                ("membership", models.CharField(max_length=100)),
                ("membership_starting_date", models.DateField()),
                ("membership_ending_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="MembershipData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration_days", models.IntegerField()),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "registration_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membership_name", models.CharField(max_length=100)),
                ("name_of_member", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField()),
            ],
        ),
    ]
