# Generated by Django 5.1.3 on 2024-11-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberdata",
            name="attendance_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memberdata",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("left", "Left")],
                default="active",
                max_length=10,
            ),
        ),
    ]
