# Generated by Django 5.1.3 on 2024-11-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0002_memberdata_attendance_details_memberdata_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdata",
            name="member_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="memberdata",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
