# Generated by Django 5.1.3 on 2024-11-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_paymentdata_member_id_alter_memberdata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberdata",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="member_images/"),
        ),
    ]
