# Generated by Django 5.1.3 on 2024-11-27 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_alter_memberdata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberdata",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="membership.membershipdata",
            ),
        ),
    ]
